# Generated by Django 4.1.7 on 2023-05-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrJours', models.FloatField()),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('montant', models.FloatField()),
            ],
            options={
                'db_table': 'Facture',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPaye', models.FloatField()),
                ('montantPaye', models.FloatField()),
            ],
            options={
                'db_table': 'Paiement',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField()),
                ('malade', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SauceQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_sauce', models.BooleanField(default=False)),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.sandwich')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.sauce')),
            ],
        ),
        migrations.AddField(
            model_name='sandwich',
            name='sauces',
            field=models.ManyToManyField(through='blog.SauceQuantity', to='blog.sauce'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('prix', models.FloatField()),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.facture')),
                ('voiture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.voiture')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='paiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.paiement'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('role', models.CharField(max_length=10)),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.facture')),
                ('voiture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('contract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.contract')),
                ('facture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.facture')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.employee')),
            ],
        ),
    ]
