# Generated by Django 4.1.7 on 2023-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='doors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
